# Generated by Django 3.0.4 on 2020-06-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200617_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pref_genere',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/images/profile_pic/default.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
