# Generated by Django 3.0.4 on 2020-06-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200621_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/images/profile_pic/default.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
