# Generated by Django 3.0.4 on 2020-06-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200624_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/default.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
