# Generated by Django 3.0.4 on 2020-06-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200624_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default/default.png', null=True, upload_to='profile_pic'),
        ),
    ]
